### ISSUE TITLE
Allow user to disable ui when used with nova packages

### ISSUE THREAD

**Issue by duckzland** [joedixon/laravel-translation#102]
**Is your feature request related to a problem? Please describe.**

Allow developer to totally disables the frontend ui, especially if they already use your nova packages.

**Describe the solution you'd like**

we can put a new config called disable_ui and then wrap the config value at web.php file

if (config('translation.disable_ui', false) {
      return;
}

Route........

**Describe alternatives you've considered**

**Additional context**

**Comment by mshossain110** [comment]
Hello @duckzland,

I agree with you. we need to have a way to disable the UI. when we work with a single page application like admin then this UI can't help us.

**Comment by joedixon** [comment]
I'm sorry it's taken so long for me to get around to this. I'll add this to the backlog for the new version targeting Laravel 9
