### ISSUE TITLE
Is the latest supported version really Laravel 5

### ISSUE THREAD

**Issue by neonovic** [joedixon/laravel-translation#109]
The documentation starts with sentence "Laravel Translation is a package for Laravel 5".
I see active latest commits.

Is the support of this package really for Laravel 5 only?
Not running on the latest Laravel 7?

Thank you

**Comment by kennonb** [comment]
Not sure if anyone else comes here for this question or not, but this package does still work on Laravel 7. 👍🏻

**Comment by sancheam** [comment]
Got an error when install on Laravel 7. 
anyone facing the same issue? 

`▶ composer require joedixon/laravel-translation
Using version ^1.1 for joedixon/laravel-translation
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   InvalidArgumentException

  Invalid driver []

  at vendor/joedixon/laravel-translation/src/TranslationManager.php:35
    31|         $driverResolver = Str::studly($driver);
    32|         $method = "resolve{$driverResolver}Driver";
    33|
    34|         if (! method_exists($this, $method)) {
  > 35|             throw new \InvalidArgumentException("Invalid driver [$driver]");
    36|         }
    37|
    38|         return $this->{$method}();
    39|     }

      +20 vendor frames
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.`

**Comment by JerryBels** [comment]
Worked for me with Laravel 8 without issues.

**Comment by Voltra** [comment]
@sancheam I got the exact same issue with Laravel 8

**Comment by Christophvh** [comment]
Comment on another issue that might help. https://github.com/joedixon/laravel-translation/issues/132#issuecomment-763737736
