### ISSUE TITLE
Can't handle files inside folder

### ISSUE THREAD

**Issue by victorsilent** [joedixon/laravel-translation#110]
**Describe the bug**
Translation manager can't handle files inside folders, it creates a copy of the file with the updates, but outside the right place.

**To Reproduce**
1. Go to your lang files
2. Create a folder there and put a file inside it
3. try to update the tokens on the translations manager website
4. Check that you have a file on your root lang files and and the file inside the folder is untouched

**Expected behavior**
Change just the file inside the folder

**Desktop (please complete the following information):**
 - OS: [UBUNTU]
 - Browser [Firefox]
 - Version [76]

**Comment by yalagin** [comment]
any update on this? I have same problem too 
![Screen Shot 2020-06-18 at 6 37 39 PM](https://user-images.githubusercontent.com/12879142/85041871-2c507280-b193-11ea-9006-58d9bcb84146.png)

**Comment by victorsilent** [comment]
@yalagin I fixed by my own, you can check here: https://github.com/victorsilent/laravel-translation/commits/master
We are using this version under production and seems fine.

**Comment by yalagin** [comment]
thanks but I already switched to another package that more popular. it did not have that problem and have an automatic translation by google translate!

**Comment by boryn** [comment]
@yalagin what do you suggest as an alternative?

**Comment by ruanpepe** [comment]
I sent a pull request and it is waiting for a review and approval.
#116
