### ISSUE TITLE
Next to none default values for Database

### ISSUE THREAD

**Issue by DubStepMad** [joedixon/laravel-translation#120]
**Describe the bug**
After following the installation guide on github and setting the driver to `database` there seems to be no default values within the database for the package.

Also I am unsure of how to get the language files into the database.

**To Reproduce**
Follow the github installation guide

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13799856/89959121-920d2800-dc33-11ea-9584-e329e03b3971.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by j33tmane** [comment]
y this issue is closed? i have same issue.
