### ISSUE TITLE
Can't Update Translation Key

### ISSUE THREAD

**Issue by Sahir-SQ** [joedixon/laravel-translation#122]
I got this error in console while updating single translation key
app.js:1 POST http://localhost/languages/ar 404 (Not Found)

it is not finding that path

**Comment by mohamad19941994** [comment]
Same problem but I have this error on server online in localhost it's work well :(

**Comment by officialmmt** [comment]
Same problem!!!!

**Comment by DevYSM** [comment]
The same problem, any solving for this?
