### ISSUE TITLE
How it is made ?

### ISSUE THREAD

**Issue by michaelkovarik** [joedixon/laravel-translation#124]
Hello,
i have just question.

What technology is used for this part of code:
`<td>
                                                    <translation-input 
                                                        initial-translation="{{ $value[$language] }}" 
                                                        language="{{ $language }}" 
                                                        group="{{ $group }}" 
                                                        translation-key="{{ $key }}" 
                                                        route="{{ config('translation.ui_url') }}">
                                                    </translation-input>
                                                </td>`

I suppose it is AJAX based. Maybe some javascript framework ?

Thank you 👍

**Comment by smares** [comment]
Vue
