### ISSUE TITLE
it doesn't publish all the required files, and showing error when trying to add translate.

### ISSUE THREAD

**Issue by debjit** [joedixon/laravel-translation#19]
It doesn't publish all the file with this method
php artisan vendor:publish --provider=JoeDixon\\Translation\\TranslationServiceProvider

When adding to translate it doesn't save showing 

URL: http://localisation.test/languages/te/translations
it takes the file path instead of urla and giving a 404 error 
The requested URL /languages/D:\file_path\localisation\resources\lang\bn/translations was not found on this server.

and got a woops warning of 
ErrorException (E_WARNING)
mkdir(): File exists

**Comment by joedixon** [comment]
Hi @debjit, I'm going to break these in to two separate issues to make progress easier to track.
