### ISSUE TITLE
Not all files are being published

### ISSUE THREAD

**Issue by joedixon** [joedixon/laravel-translation#20]
@debjit reported the following

It doesn't publish all the file with this method

php artisan vendor:publish --provider=JoeDixon\Translation\TranslationServiceProvider

**Comment by joedixon** [comment]
Hi @debjit, can you let me know the files which are not being published?

**Comment by debjit** [comment]
Tthere are no file in public folder of laravel.
I am using w10 with laragon.

**Comment by joedixon** [comment]
The assets should be published to `public/assets/vendor/translation` - can you check in there?

**Comment by debjit** [comment]
Yes I have to run 
php artisan vendor:publish 
two times after nothing in public folder.

**Comment by joedixon** [comment]
Can you try the following:

`php artisan vendor:publish --provider="JoeDixon\Translation\TranslationServiceProvider"`

Notice the addition of the double quotes.

**Comment by debjit** [comment]
Yes. It shows " Published Successfully".

**Comment by joedixon** [comment]
So is this working now? I notice in the screenshot from your other issue that the styling is being pulled through so it looks as though they are loading correctly.
