### ISSUE TITLE
Scanner doesn't allow whitespace before/after a param

### ISSUE THREAD

**Issue by jmiller42ce** [joedixon/laravel-translation#235]
`
__(
    'This will also go in the JSON array'
)`

This pattern will not be detected by the scanner since it contains whitespace surrounding the param. 

**Expected behavior**
Scanner should detect translation function with whitespace before/after param

version: 2.0

**Comment by jmiller42ce** [comment]
Created PR #236 to solve.

**Comment by jmiller42ce** [comment]
@joedixon friendly bump- our org could use my fork but I'd really prefer to stick with your original repo to stay up-to-date. Thanks!

**Comment by joedixon** [comment]
Just tagged v2.1.2 with your fix. Thank you!
