### ISSUE TITLE
facing problem while installing with laravel 9

### ISSUE THREAD

**Issue by isalman-khan** [joedixon/laravel-translation#239]
when i try to install it in the laravel 9 i face the following error. any idea how can it be solved 

```  Problem 1
    - joedixon/laravel-translation[v2.0, ..., 2.x-dev] require illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires joedixon/laravel-translation ^2.0 -> satisfiable by joedixon/laravel-translation[v2.0, 2.x-dev].
```

**Comment by malozaibi** [comment]
I have the same issue, I wish if you can add support for Laravel 9 as well as support for Vite instead of mix.

**Comment by joedixon** [comment]
Hey @isalman-khan - can you give it a try now?

**Comment by joedixon** [comment]
> as well as support for Vite instead of mix.

Hey @malozaibi - Why do you need support for Vite, you don't need to build any of the assets?

**Comment by joedixon** [comment]
Closing as no reply. Feel free to reopen if you still have an issue.
