### ISSUE TITLE
Use `/lang` instead of `/resources/lang`

### ISSUE THREAD

**Issue by efectn** [joedixon/laravel-translation#246]
**Describe the bug**
If laravel-translation package shares languages to `resources/lang`, Laravel uses `resources/lang` as default langPath (you can check it by using `app()->langPath()`). And then, it causes problem if we don't put any language files in `resources/lang`.

**Expected behavior**
Package should use `lang` as default language path.

**Screenshots**
![2022-09-02_20-57](https://user-images.githubusercontent.com/45270788/188211214-0c665efd-f6a4-4b27-ba7c-e806afb39925.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser Chrome
 - Version 104

If you're OK, i can create a PR for this :rocket:

**Comment by ProfConsulting** [comment]
True. Vote +1

**Comment by HayderThamer92** [comment]
True. Vote +1

**Comment by HayderThamer92** [comment]
True. Vote +1

**Comment by joedixon** [comment]
A PR would be great 🙌

**Comment by ruwad-co** [comment]
True. Vote +1

**Comment by riomigal** [comment]
Just as an info, since I had similiar issue. You need just to delete the directory /resources/lang (copy existing files if needed in /lang). Laravel and the plugin use automatically the /lang folder...
