### ISSUE TITLE
Using Auth middleware cause redirect to login everytime

### ISSUE THREAD

**Issue by malozaibi** [joedixon/laravel-translation#248]
**Describe the bug**
Using the Auth middleware make the /languages link to redirect to login and never return to the page. (it keeps returning to login after each successful login)

**To Reproduce**
1. Go to config/translation.php
2. change the middleware from web to auth
 `'route_group_config' => [ 'middleware' => 'auth', ],`
3. go to /languages 
4. it will redirect to login
5. login and it will show login again and again

**Expected behavior**
It should open the /languages after login or if previously logged in show it immediately   

** versions **
 - OS: MacOS 12
 - Browser all
 - Laravel 9

Please fix it, Thank you

**Comment by joedixon** [comment]
To confirm, are you able to access the `/languages` route manually after logging in?

**Comment by malozaibi** [comment]
> To confirm, are you able to access the `/languages` route manually after logging in?

Yes it redirect to the home 

Note: I am using laravel/ui bootstrap auth 

I was able to solve this issue manually by cuting the routes form your route file and past them in my own route with middleware auth

**Comment by dansleboby** [comment]
Full step top reproduces

```
composer create-project laravel/laravel .
compsoer require laravel/ui
php artisan ui bootstrap --auth
npm install
npm run build
@ set the DB in .env
php artisan migrate
composer require joedixon/laravel-translation
php artisan vendor:publish --provider="JoeDixon\Translation\TranslationServiceProvider"
@ edit translations.php and add auth middleware
```

**Comment by dansleboby** [comment]
I found the issue, because the route is outsite the web.php in this case a external package, the auth middleware need to be run with web

Thanks to https://stackoverflow.com/questions/35160144/authuser-returns-null

So if you set it like this it work fine

```php
'route_group_config' => [
    'middleware' => ['web', 'auth'],
],
```

I hope it will help!

**Comment by malozaibi** [comment]
Thank you very much @dansleboby this solution worked for me.
