### ISSUE TITLE
Login seems not to work with Filament

### ISSUE THREAD

**Issue by GuyVervillePerso** [joedixon/laravel-translation#249]
**Describe the bug**
When choosing the 'auth' middleware, the package cannot read the actual Filament login path, which is /admin/login.

**To Reproduce**
1. Install Filament
2. Install your package
3. Go to /languages
4. Error /login not defined

**Expected behavior**
Should be redirected to /admin/login

**Screenshots**
![CleanShot 2022-09-15 at 22 00 22](https://user-images.githubusercontent.com/69694028/190540234-8d4ccd7e-87d2-4a2c-aeed-3685ba59362f.png)

**Additional context**
Trying a redirect in /routes/web.php of /login to /admin/login works, but it doesn't go back then to /languages

**Comment by joedixon** [comment]
Hey @GuyVervilleSpiria - the `auth` middleware is provided by Laravel so you may whish to look at how to redirect users: https://laravel.com/docs/9.x/authentication#redirecting-unauthenticated-users
