### ISSUE TITLE
Rerquest: Auto translation is missing.

### ISSUE THREAD

**Issue by debjit** [joedixon/laravel-translation#25]
Hello, I would love to see 2 things in this packagea.a
1. Auto-translation 
When created translation, it will automatically convert from google or Yasna or similar type of free translation services. That will help the user to create more easily and quickly. With just one click.
2. Auto chose language(From the drop-down page) test page.

**Comment by joedixon** [comment]
Hi,

At this stage, I don't have plans to add auto-translation to the package.

Can you elaborate a little more on what you mean by the 'auto choose language'?

**Comment by joedixon** [comment]
I feel like this is out of the scope of what I what I want from this package right now, but will keep in mind for the future.

I'll also try to work on the documentation.

Thanks for your feedback.
