### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by ArnoutXYZ** [joedixon/laravel-translation#267]
- joedixon/laravel-translation[v2.1, ..., v2.1.2] require illuminate/support ^8.0||^9.0 -> satisfiable by illuminate/support[v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4].

- Only one of these can be installed: illuminate/support[v5.0.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.4, v10.0.0, ..., v10.1.4], laravel/framework[v10.0.0, ..., v10.1.4]. laravel/framework replaces illuminate/support and thus cannot coexist with it.

Would be much appreciated if we are able to use the translations combined with Laravel 10 :)

**Comment by chrillep** [comment]
@joedixon ping

**Comment by ArnoutXYZ** [comment]
Another @joedixon ping maybe?

**Comment by yyqsg888** [comment]
@joedixon ping
