### ISSUE TITLE
5.4 not working

### ISSUE THREAD

**Issue by bsormagec** [joedixon/laravel-translation#27]
Not working on 5.4 do you have any idea about it not publishing any configuration ?

**Comment by joedixon** [comment]
Hi, what is the command you are running?

**Comment by bsormagec** [comment]
its not working with folder in folder structure for example,
en -> admin -ı
                 categories -ı
                             general.php

its overwriting all generals.php and i can't choose what i want to use in categories or other subdirectories.

**Comment by joedixon** [comment]
At the moment, this package doesn't work with nested language directories. Would be open to a pull request if you are interested?

What do you mean by overwriting general.php?
