### ISSUE TITLE
Nova Package

### ISSUE THREAD

**Issue by zek** [joedixon/laravel-translation#28]
Hey @joedixon, good job on the project. I like it very much.

Do you have any plan to integrate into Laravel Nova?

**Comment by joedixon** [comment]
It's definitely in my pipeline, but I don't know when it will be. I'll keep you updated.

**Comment by joedixon** [comment]
I'm not far off finishing my first version of the Nova package. Are you interested in testing it?

**Comment by zek** [comment]
Cool. Yeah I can test it.

**Comment by joedixon** [comment]
Great, I just need to finish a couple of bits and tidy it up and then I'll fire it over.

**Comment by zek** [comment]
Can't wait for it :)

Let me know when you release. Is it gonna be in a new repository?

**Comment by joedixon** [comment]
Yeah, it will be a new repo

<img width="995" alt="screenshot 2018-11-29 at 19 38 09" src="https://user-images.githubusercontent.com/3438564/49247115-6bcb3880-f40e-11e8-882f-b8d2e8a64b66.png">

**Comment by joedixon** [comment]
I've run into an issue where Nova uses JSON language files in the vendor directory which this package doesn't support at the moment. Unfortunately, there's a fair amount of refactoring needed to make this happen so I won't be able to get this over to you as quickly as I'd have liked. I'll keep you posted.

**Comment by zek** [comment]
Can you publish the repository? I may help you

**Comment by joedixon** [comment]
OK, just pushed it all up, but it's really rough around the edges.

The Nova tool can be found here: https://github.com/joedixon/nova-translation

As I mentioned, there is quite a big rewrite under the hood so I have created a new branch of the Laravel Translation package which the Nova tool uses - `vendor-json-files`.

Hopefully the correct branch will automatically get installed when you `composer update`.

Let me know if any issues.

Thanks again,
Joe

**Comment by zek** [comment]
It seems it works. Is there any problem you encountered? Is there anything I can do?

**Comment by joedixon** [comment]
Haven't encountered anything, but great to have another set of eyes.

To be honest, I'm more worried I've introduced bugs to the main Laravel Translation package so if you have time to test that on the `vendor-json-files` branch, I'd really appreciate it.

Other than that, nothing else to do other than tidy, merge and publish which I hope to get done later in the week.

Does it work how you expected?

**Comment by joedixon** [comment]
Hey @zek, just published the package https://novapackages.com/packages/joedixon/nova-translation

Would be grateful for any feedback and even more grateful for a nice review 😉
