### ISSUE TITLE
Migration failed

### ISSUE THREAD

**Issue by robov** [joedixon/laravel-translation#29]
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'language' cannot be null (SQL: insert into `languages`

**Comment by joedixon** [comment]
Do you have a value set for `locale` set in your `app.php` file?

**Comment by mydnic** [comment]
Even with the `locale` having a value in `app.php` I had the issue. I found out that it was because in my `AppServiceProvider` I was setting the app Locale from the url like this 

```php
public function boot()
{
    app()->setLocale(request()->segment(1));
}
```

I fixed it by checking if the app is running in the console

```php
public function boot()
{
    if (!app()->runningInConsole()) {
        app()->setLocale(request()->segment(1));
    }
}
```

And then the migration works fine 👍
