### ISSUE TITLE
Database storage not working

### ISSUE THREAD

**Issue by FrankyJust** [joedixon/laravel-translation#33]
**Describe the bug**
Database storage not working

**To Reproduce**
Initially I saved new language to file. Then I've followed all the instructions to save new languages to database in stead of a file. But a new added language is still being added as a file.

**Desktop (please complete the following information):**
 - OS: OSX Mojave
 - Browser: Safari

**Comment by joedixon** [comment]
Can you just confirm the following:
- You have set the driver to `database` in the config
- The database tables have been migrated and exist in the database

Thanks,
Joe

**Comment by FrankyJust** [comment]
Yes, both are implemented.

**Comment by joedixon** [comment]
Does anything get added to the database?

**Comment by FrankyJust** [comment]
No, nothing is added. Only the default en-language is visible in languages-table.

**Comment by joedixon** [comment]
Hmm, I'm not sure what the issue could be. Have you published the `translation.php` file. Are you able to send it across so I can have a look?

**Comment by FrankyJust** [comment]
yes, file is published. I've added it in a zip.
[translation.php.zip](https://github.com/joedixon/laravel-translation/files/2644171/translation.php.zip)

**Comment by joedixon** [comment]
That looks fine. Can you add the following to your app (in a route or controller is usually a good place) and let me know the output:

```
dd(config('translation.driver'));
```

**Comment by FrankyJust** [comment]
I've tried some files in the app, but I don't get any result, or sometimes an error. So I will wait until the full tutorial on Laravel News is ended, and will try then your app again.

**Comment by mustafatoker** [comment]
This problem is keep going on. 

**Environment:**
Laravel 5.8
PHP 7.3
MySQL 5.7

**Comment by Atif-Bashir-1998** [comment]
@FrankyJust @mustafatoker  check the updated documentation and [this issue](https://github.com/joedixon/laravel-translation/issues/228)
