### ISSUE TITLE
Migration Class Name Conflict

### ISSUE THREAD

**Issue by OzanKurt** [joedixon/laravel-translation#37]
![image](https://user-images.githubusercontent.com/8682003/50425875-7c40c880-087f-11e9-9531-669aaf4f3438.png)
The migration class name conflicts with my own languages table. That table should be prefixed and there should be an option to disable database migrations of the package if the database provider is not being used.

**Comment by OzanKurt** [comment]
This should be enough for a quick fix for people who doesn't use the `database` driver.
```php
        if (config('translation.driver') == 'database') {
            $this->loadMigrationsFrom(__DIR__.'/../database/migrations');
        }
```

**Comment by joedixon** [comment]
I'd be happy to accept this as a pull request.

As for the conflicting table names, you can override them by updating the `languages_table` and `translations_table` options in the package config file.

**Comment by OzanKurt** [comment]
@joedixon Enjoy!
https://github.com/joedixon/laravel-translation/pull/38

**Comment by joedixon** [comment]
Thanks @OzanKurt, this is great.

The only question I have is whether the conflict is due to the table name and/or the class name of the migration? 

The reason I ask is that updating the class and file name of the migrations causes a breaking change to those who have already installed the package as rolling back the migrations will fail. I don't really want to bump the major version for this.

Thanks for the Turkish translations too 👌

**Comment by OzanKurt** [comment]
Sadly yes, it conflicts with the other migration class names. Is it somehow possible to make migrations work with namespace?

**Comment by joedixon** [comment]
Sorry for the delay on this. I've been busy having a baby!

I don't have a solution for this at the moment other than to ask you to rename the migration you have in your application.

I don't want to lose the other parts of your PR. Are you happy I cherry pick these (Turkish translations, conditional loading of migrations etc) or do you want to resubmit the PR?

**Comment by joedixon** [comment]
Closing this for now, but let me know if you have any more thoughts on the above.

**Comment by Sitethief** [comment]
`namespace database\migrations;`

Placing this in my own migration solved this exact problem in my code.
