### ISSUE TITLE
command (not readme) typo: sync-missing-tranLSation-keys

### ISSUE THREAD

**Issue by cirdog** [joedixon/laravel-translation#40]
**Describe the bug**
The command **signature** also has the **same typo** as the readme that got fixed previously.

**To Reproduce**
1. type:  php artisan translation:sync-missing-tranSLation-keys
2. it tells me wrong command.

**Expected behavior**
The typo in command signature should also be fixed, so we can properly use the command.

**Screenshots**
```
    protected $signature = 'translation:sync-missing-tranlsation-keys {language?}';
```

**Desktop (please complete the following information):**
 - OS: ANY
 - Browser Chrome
 - Version 71

**Comment by joedixon** [comment]
Thanks for this, there is a fix coming in the next release.

**Comment by joedixon** [comment]
#35 has been merged and resolves this issue.
