### ISSUE TITLE
Downloading to and uploading from excel sheets or word files

### ISSUE THREAD

**Issue by Jeroenvanderholst** [joedixon/laravel-translation#43]
**Is your feature request related to a problem? Please describe.**
I have to manage multiple languages, and my application has turned a bit large. I don't speak 26 languages, so I rely heavily on native speakers or translation agencies. When I want them to help me with my translations, it is better to provide an excel sheet. So nowadays I build excel sheets by stripping the JSON data by hand and with some nice concat functions I reconstruct the JSON, and place it manually into the DEV-STG-UAT and Live environments.
This workflow has no use of the sync-missing-translations artisan command that is most helpfull. So my team now needs to maintian a list of translations in confluence for us to keep track. It is very easy to make mistakes here.

**Describe the solution you'd like**
I would like to have a export / import functionality to EXCEL sheets with the key in column A and all translations or maybe only the source and target language in columns B and beyond. This way we can ship this to non-coders like regular sales colleagues, secretaries, or translating agencies.

**Describe alternatives you've considered**
See problem description.

**Additional context**
I really like your approach on this subject. And your code base looks great and very tidy. So I'll stick with your package and would like to help you take this further.

**Comment by joedixon** [comment]
I like this idea (have had to build something similar on previous projects)

Do you want this feature just for missing translations or for everything?

I'm happy to build this out, but I don't know when I'll be able to get to it. If you're interested in submitting a PR, I'm happy to discuss how to tackle the problem.

**Comment by Jeroenvanderholst** [comment]
Hi Joe, I would be interested into submitting a PR, but I have to warn you.. I might not be able to pull this off by myself, and I don't have much freetime to spare, so if you can be patient, let's give it a go... 
I do have an idea on how to approach it though: We could use maatwebsite's package for exporting and importing to excel. https://github.com/Maatwebsite/Laravel-Excel

We could only support the export and import using translations stored in the database for now owuld you say?

**Comment by joedixon** [comment]
Sorry for the delay in getting back to you. I've been busy having a baby!

I think it would make sense to use that package.

We have all the functionality in the drivers to get the translations from either file or database so from that respect, it shouldn't really matter.

Would you want an option in the UI to be able to carry out the export and import?

**Comment by Jeroenvanderholst** [comment]
Well that is great news. I am just as busy, allthough my babies are 15, 17 and 19 years old ;) But my day-job is preventing me from being very active.

Yes a button in the UI would definately be usefull. I could do with CLI-command, but for main-stream users it would be a good addition.

**Comment by Jeroenvanderholst** [comment]
If you are suffering from lack of sleep, just give me an idea on how to approach this feature extension and let me play around with the code. I can then maybe do my first serious pull request in a couple of weeks.

**Comment by plenartech** [comment]
Hi Joe - is this feature still under consideration? It would be a great addon, as we can share it with different customers or freelancers who can add translation for specific language in Excel separately and then we can import back to our system.

Thanks in advance!

**Comment by joedixon** [comment]
I'm sorry it's taken so long for me to get around to this. I'm planning to refresh this package for Laravel 9 and will add this feature to my backlog. Closing for now.
