### ISSUE TITLE
Better navigation between parts of the tutorial

### ISSUE THREAD

**Issue by LarBearrr** [joedixon/laravel-translation#45]
**Is your feature request related to a problem? Please describe.**
No, this relates more to the tutorial I found on laravelnews.com

**Describe the solution you'd like**
It woud be helpful to be able to easily navigation between the various parts of the tutorial. After [Part 2](https://laravel-news.com/scaffolding-a-package/), there is no link to the next part. 

**Describe alternatives you've considered**
Starting from the latest part that was published, I had to work backwards using the link at the beginning of each part.

**Comment by joedixon** [comment]
Hi,

I'll feed this back to Eric @laravelnews.

Thanks,
Joe
