### ISSUE TITLE
Support for nested arrays

### ISSUE THREAD

**Issue by pancevac** [joedixon/laravel-translation#47]
I use validation files that have nested arrays. In short, nested arrays aren't visible or editable in translation manager list. I also tried to replace arrays with "." string but then it's only visible, not editable... 

It would be nice if someone could modify package to support nested arrays or there is alternative?

**Comment by joedixon** [comment]
This is on the roadmap. My time is limited at the moment so will take me a while to get round to it.

Would be more than happy to accept a PR if anyone has the time.

**Comment by joedixon** [comment]
I released v0.2.0 today which adds support to this. Thanks to @ahferriz for the [PR](https://github.com/joedixon/laravel-translation/pull/53)
