### ISSUE TITLE
if the [key] contains a full-stop (period) then the [key] is concatenated in the generated language files.

### ISSUE THREAD

**Issue by rominronin** [joedixon/laravel-translation#55]
**Description**
We're using the library on a rebuild project with thousands of translation lines, about half of the keys have a full-stop either in the middle of the key name or at the end.

When running the database -> file sync command, any characters after the first full-stop (inclusive) in the key name are dumped in the generated files, so for example:

group = "newsletter"
key = "Welcome. Your name."
value = "Welcome. Please enter your name."

would be represented in the lang file as follows:
`return [
  "Welcome" => "Welcome. Please enter your name."
]`

Instead of:
`return [
  "Welcome. Your name" => "Welcome. Please enter your name."
]`

**To Reproduce**
Ensuring you have a key containing a full-stop (period), simply run the sync command from database to file:

`php artisan translation:sync-translations`

**Expected behavior**
I expect that the key should be copied in full to the generated file, full-stops and all.

**Desktop (please complete the following information):**
 - Ubuntu, 16.04
 - CentOS, not sure which version

**Comment by joedixon** [comment]
This is a weird one. I'll take a look.

**Comment by joedixon** [comment]
Which version are you running?

**Comment by rominronin** [comment]
From the composer.jspn file:
```json
	"require" : {
		"php" : "^7.1.3",
		"joedixon/laravel-translation" : "^0.1.4",
		"joedixon/nova-translation" : "^0.1.1",
		"laravel/framework" : "5.7.*"
	}
````

I included the packages which I thought might be relevant above, I could include them all if it'll help.

**Comment by joedixon** [comment]
The issue is that the package sees this as a nested translation using dot notation.

I think I have found a workaround and will try and get it patched this week.

**Comment by joedixon** [comment]
Sorry for the delay @rominronin - can you try upgrading and checking your issue is resolved?
