### ISSUE TITLE
Files in subdirectory don't get saved in the subdirectory

### ISSUE THREAD

**Issue by stefnats** [joedixon/laravel-translation#56]
Hi,

first thanks for this awesome package.

When i edit a translation for the file, let's say, homepage/faq.php it will be displayed as "faq" in the first column.
Changes are saved in the root directory of the language files for the locale and not in the en/homepage/faq.php file but in the en/faq.php which didn't exist before.

**Comment by joedixon** [comment]
The package doesn't support nested translation files at this time. I'd be open to a PR to add this functionality.
