### ISSUE TITLE
Dont's use "/" or "\" in geting vendor name

### ISSUE THREAD

**Issue by vFire** [joedixon/laravel-translation#57]
in Dirvers/file.php

It will be better use as following:

> $vendor = str_before(str_after($file->getPathname(), 'vendor'.DIRECTORY_SEPARATOR), DIRECTORY_SEPARATOR);

User DIRECTORY_SEPARATOR not "/" or "\" since it is different between in linux and in windows.

**Comment by joedixon** [comment]
Very valid point, I'll get this patched ASAP.

**Comment by joedixon** [comment]
Fixed and included in v0.2.1
