### ISSUE TITLE
Group name should be searchable is better in single type

### ISSUE THREAD

**Issue by vFire** [joedixon/laravel-translation#58]
in Drivers/Translations.php

        return $allTranslations->map(function ($groups, $type) use ($language, $filter) {
            return $groups->map(function ($keys, $group) use ($language, $filter, $type) {
                return collect($keys)->filter(function ($translations, $key) use ($group, $language, $filter, $type) {
                    return strs_contain([$group, $key, $translations[$language], $translations[$this->sourceLanguage]], $filter);
                });
            })->filter(function ($keys) {
                return $keys->isNotEmpty();
            });
        });

this could make group name searchable, especially very useful in single type translation.

**Comment by joedixon** [comment]
This makes sense. I'll get an update rolled out ASAP.

**Comment by joedixon** [comment]
Fixed and included in v0.2.1
