### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by akhalid4493** [joedixon/laravel-translation#69]
**I can't find languages route*

My App has middleware that redirect the url into  : http://webapp.test/{locale}
if I need this route : http://webapp.test/languges it will redirect to : http://webapp.test/{locale}/languges and it return page not found 

<img width="1440" alt="Screen Shot 2019-06-22 at 5 47 24 PM" src="https://user-images.githubusercontent.com/45354705/59965394-fba11300-9515-11e9-9024-628b6f597ad0.png">
<img width="1440" alt="Screen Shot 2019-06-22 at 5 48 12 PM" src="https://user-images.githubusercontent.com/45354705/59965395-fba11300-9515-11e9-9b98-0a689de4618e.png">

**Comment by akhalid4493** [comment]
I found solution for my issue but I need some help from u  

<img width="1440" alt="Screen Shot 2019-06-23 at 12 22 15 AM" src="https://user-images.githubusercontent.com/45354705/59969032-10e56400-954d-11e9-9d06-08fe1dd34052.png">


when using terminal the app said :   Class request does not exist , the segment solve my problem
:D

**Comment by joedixon** [comment]
So is this all resolved now?

**Comment by akhalid4493** [comment]
yes it works but only open english ui as domain.test/en/languages/ar/translations 

- I had localized middleware if I open my site as domain.test/ar then try open language ui it will return to en locale but I can't understand why this case happen & I changed the ui_url :    
 'ui_url' => ''.app()->getLocale().'/languages',
 
 I can't implementation  my localized middleware on your package , u must upgrade this awesome package to accept the developers that use his own localized middleware , thanks bro for your great job 👍
