### ISSUE TITLE
Cache database values

### ISSUE THREAD

**Issue by core45** [joedixon/laravel-translation#75]
**Is your feature request related to a problem? Please describe.**
It looks like if the translation are stored in DB, every time a translation is needed the database is searched for it. This can slow down the site significantly. I can not see any caching for the queries.

**Describe the solution you'd like**
Add caching.

**Comment by joedixon** [comment]
This is something I would like to add, but I'm a little strapped for time at the moment. Would you be interested in submitting a PR?

**Comment by rogierverbrugge** [comment]
I've got the same problem, logged my queries and my nova pages has 17.000 requests to my database. Got timeout on production.

**Comment by virgixas** [comment]
Possibility to override default Language and Translation Models or configure to use own ones would solve cache stuff, if i was able to add to model : use Cacheable; (genealabs/laravel-model-caching), just tried that localy and it works nice.

**Comment by vortechron** [comment]
just having this problem, your suggestion might work @virgixas . need the ability to configure our own custom model hm

**Comment by vortechron** [comment]
for now i just override JoeDixon\Translation\Drivers\Translation binding and replace and inject a custom database driver with my own translation model.

```
        $this->app->singleton(Translation::class, function ($app) {
            return (new TranslationManager($app, $app['config']['translation'], $app->make(Scanner::class)))->resolve();
        });
```

**Comment by m7vm7v** [comment]
Hey, I know it's been some time but has there been an easier solution than overriding the model?
Hopefully, there might be a fork or it has been already built in.
If not then can we get an example of the new model file?

Thanks

**Comment by legreco** [comment]
@virgixas it partially works, translation are cached in redis but each time i modify a translation in the UI, translation is added in the database and for some reason cache is not updated
