### ISSUE TITLE
Translating multi tenant app

### ISSUE THREAD

**Issue by emilas44** [joedixon/laravel-translation#76]
**Is your feature request related to a problem? Please describe.**
The problem is that we have more than 500 databases and I am not sure how to implement this so we can translate all the keys we have.

**Describe the solution you'd like**
I don't actually know. My question is actually: Can this package be used for a multi tenant platform or it's working only with a single database?

I would be happy if we could discuss this in 5 min so I could understand if this is something for us or not?

**Comment by joedixon** [comment]
Sorry for taking so long to get back to you. The package connects to the database your app is connected to so provided your translations were in each tenant db, I don't think there should be an issue. I may not be fully understanding your setup though.
