### ISSUE TITLE
nested translation keys

### ISSUE THREAD

**Issue by VBrueggemann** [joedixon/laravel-translation#77]
I have a lot of nested keys in my translation file e.g.
```
'content' => [
    'text' => 'text',
    'headline' => 'headline'
]
```
to get to a specific key it is possible to do `__('content.text')`.
But if I am outside of the Laravel Blade context (e.g. in a Vue component)
I would like to give this component all relevant translations `__('content')`
This does not work with the Database Driver.
The database itself looks like this:

| key | translation |
| ---- | ---- |
| content.text | text |
| content.headline | headline |

If a non-leaf translation is requested all sub translations should be returned as an array.
`__('content')` => `['text' => 'text, 'headline' => 'headline']`

The solutions to this problem are either to explicitly request every single translation or to overwrite the ServiceProvider and DatabaseLoader.

The changed Logic in the DatabaseLoader currently looks like this:
```
 public function load($locale, $group, $namespace = null)
 {
   [...]
            return $this->translation->getGroupTranslationsFor($locale)->filter(function ($value, $key) use ($group) {
                return $key === $group;
            })->first();
   [...]
    }
```

I propose changing it to:

```
 public function load($locale, $group, $namespace = null)
 {
   [...]
            $dotted = [];
            $this->translation->getGroupTranslationsFor($locale)->filter(function ($value, $key) use ($group) {
                return $key === $group;
            })->first()->each(function ($key, $translation) use (&$dotted) {
                Arr::set($dotted, $translation, $key);
            });
            return collect($dotted);
   [...]
    }
```

**Comment by joedixon** [comment]
I'm really sorry for taking so long to get back to you on this.

I really like this solution. If you are still using the package, would you be interested in submitting a PR?
