### ISSUE TITLE
Laravel 6.0 support

### ISSUE THREAD

**Issue by affektde** [joedixon/laravel-translation#78]
**Describe the bug**
Laravel 6.0: All str_ and array_ helpers have been moved to the new laravel/helpers Composer package and removed from the framework.
`Call to undefined function JoeDixon\Translation\Drivers\str_contains()` happens.

`composer require laravel/helpers`
will fix this issue. But I think codebase should move to `Illuminate\Support\Str` too. So we can remove the legacy package again ^^

**To Reproduce**
1. Install Laravel 6.0
2. Open translations
3. See exception of the `/nova-vendor/nova-translation/languages/de/translations` http call.

**Expected behavior**
no 500

**Additional context**

**Comment by affektde** [comment]
Ah soowwy. It's a thing with your Nova package.

`src/Http/Controllers/LanguageTranslationController.php` contains a `str_contains()` helper function ;-)

**Comment by joedixon** [comment]
It's probably both to be honest. I'll try and get them both updated for Laravel 6 ASAP.

**Comment by joedixon** [comment]
The package now supports Laravel 6 (and has for some time, sorry for the delay in getting back to you).
