### ISSUE TITLE
Can't update translation

### ISSUE THREAD

**Issue by devdodiya** [joedixon/laravel-translation#87]
I've installed the package as per git readme file and i moved the dev version of my project to LIVE 

So i need to change my dev public index.php and .htaccess to root directory

now if i change in local machine with php artisan serve it works fine but when i try in my live project it doesnt work and say 

POST http://mysite.com/lang/en 404 (Not Found)

All i changed is copied those two files to root directory

Laravel verison is 6.6.0

**Comment by joedixon** [comment]
Hi, what do you mean by 'change your dev index.php'?

**Comment by devdodiya** [comment]
Means i've just changed the location of the files, i.e. root location, by default both are stored in root/pulic directory and in my current setup it's moved to root directory
