### ISSUE TITLE
i can't install it on laravel 6

### ISSUE THREAD

**Issue by BOLYAC** [joedixon/laravel-translation#92]
**Describe the bug**
when i try to install it i get this.

**Laravel 6:**

**Additional context**
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Symfony\Component\Debug\Exception\FatalThrowableError  : Unsupported operand types

  at C:\wamp64\www\laravel\myproject\vendor\joedixon\laravel-translation\routes\web.php:3
    1| <?php
    2|
  > 3| Route::group(config('translation.route_group_config') + ['namespace' => 'JoeDixon\\Translation\\Http\\Controllers'], function ($router) {
    4|     $router->get(config('translation.ui_url'), 'LanguageController@index')
    5|         ->name('languages.index');
    6|
    7|     $router->get(config('translation.ui_url').'/create', 'LanguageController@create')
    8|         ->name('languages.create');
    9|

  Exception trace:

  1   require()
      C:\wamp64\www\laravel\myproject\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php:77

 2   Illuminate\Support\ServiceProvider::loadRoutesFrom("C:\wamp64\www\laravel\myproject\vendor\joedixon\laravel-translation\src/../routes/web.php")
      C:\wamp64\www\laravel\myproject\vendor\joedixon\laravel-translation\src\TranslationServiceProvider.php:77

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by BOLYAC** [comment]
I fix it !! my bad

**Comment by kennonb** [comment]
I ran into this issue too, and it was because I had my config cached. After clearing the config cache and installing, it all worked wonderfully. 👍🏻
