### ISSUE TITLE
Target [JoeDixon\Translation\Drivers\Translation] is not instantiable while building [JoeDixon\Translation\Http\Controllers\LanguageController].

### ISSUE THREAD

**Issue by Bojan121** [joedixon/laravel-translation#96]
After installing the newest 1.1.0 version, when trying to open the web interface I'm getting this error:
`Illuminate\Contracts\Container\BindingResolutionException
Target [JoeDixon\Translation\Drivers\Translation] is not instantiable while building [JoeDixon\Translation\Http\Controllers\LanguageTranslationController]`

I'm guessing it has something to do with the commit from @joedixon  from 6 days ago "Add multiple service providers"?

Tried `php artisan config:clear` and `php artisan clear-compiled`

Using Laravel 6.13

**Comment by joedixon** [comment]
Hi @Bojan121,

I think the issue is that I added a new service provider to the composer.json and Laravel can't find it. Can you try removing the package and reinstalling it?

**Comment by Bojan121** [comment]
Hey @joedixon, yeah tried that already but it's the same result.

**Comment by Bojan121** [comment]
@joedixon if I put the code from `TranslationBindingsServiceProvider@registerContainerBindings` into my own `appServiceProvider@register` it work fine.
Not sure why is it not registering itself?

**Comment by joedixon** [comment]
Hi @Bojan121 

Thanks for this. Unfortunately, that was the cause of another issue when using the database driver.

I have tested, and this version definitely works for me.

I'm keen to know whether Laravel sees both service providers for you. Are you able to add a `dd()` statement to both and see if they both execute? If not, I think there is a caching issue related to the following block of the composer.json:

```
"extra": {
        "laravel": {
            "providers": [
                "JoeDixon\\Translation\\TranslationServiceProvider",
                "JoeDixon\\Translation\\TranslationBindingsServiceProvider"
            ]
        }
    }
```

**Comment by tdicknet** [comment]
@joedixon I have the same problems, even in a clean laravel project... 

Where should I place the dd() ? just getting blank white pages at booting and register..

**Comment by joedixon** [comment]
Hi, I just tagged v1.1.1 which should address this.

Can you bump and let me know?

**Comment by Bojan121** [comment]
@joedixon Works for me Joe! Thank you.

**Comment by joedixon** [comment]
Great, sorry for the downtime and thanks for your input :-)
