### ISSUE TITLE
package is ignoring many @lang("Some work") method for many pages

### ISSUE THREAD

**Issue by dani821** [joedixon/laravel-translation#99]
I'm using the @lang method in my blade files and when I try to translate thee words then they are not showing in the list.
Some of the words with the @lang method are visible but some or not.

**Comment by Nalem14** [comment]
Same problem here. Have you found a solution ?

**Comment by BoGnY** [comment]
i've the same problem

**Comment by dani821** [comment]
no, I could not find the solution but instead, i used another package which
is laravel translation manager.
https://github.com/barryvdh/laravel-translation-manager


>

**Comment by gdebrion** [comment]
Hey,

I had missing translations with `@lang`, so I adjust the config file :

> 'translation_methods' => ['trans', '__', '@lang'],

Then `php artisan translation:sync-missing-translation-keys` and everything is fine!

**Comment by dani821** [comment]
Thanks for the update!
